# pytorch and numpy

NumPy and PyTorch are two fundamental libraries in the Python ecosystem, widely used in scientific computing, data analysis, and machine learning, particularly deep learning. While they share some conceptual similarities, their primary focuses and capabilities differ.

* Data in NumPy , want in python tensor ->
`torch.from_numpy(ndarray)`

* PyTorch tensor , want in NumPy -> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

In [ ]:
numpy_array = np.arange(1.0 , 11.0)
numpy_array , numpy_array.dtype

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), dtype('float64'))

In [ ]:
tensor_from_nparray = torch.from_numpy(numpy_array)
tensor_from_nparray , tensor_from_nparray.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64),
 torch.float64)

In [ ]:
# if we change something in array it will not reflect in pytorch
numpy_array = numpy_array + 1
numpy_array , tensor_from_nparray

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

When creating a NumPy array without explicitly specifying the dtype, NumPy attempts to infer the most appropriate data type based on the input values. **(default dtype)**

For **integers**:
the default data type is typically int64 on most modern 64-bit systems, or int32 on 32-bit systems. This corresponds to the size of a C long on the specific platform.

For **floating-point numbers**:
If the array contains floating-point numbers, the default data type is typically float64, which represents double-precision floating-point numbers.

In [ ]:
pytorch_array = torch.arange(1.0 , 11.0)
pytorch_array , pytorch_array.dtype

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.float32)

In [ ]:
nparray_from_pytorch = pytorch_array.numpy()
nparray_from_pytorch , nparray_from_pytorch.dtype

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32),
 dtype('float32'))

The default floating-point data type for PyTorch tensors (often referred to as PyTorch arrays) is torch.float32. This corresponds to a 32-bit single-precision floating-point number.

`Warning` : when converting from numpy -> pytorch , pytorch reflects numpy's default dtype unless specified and vice versa

In [ ]:
# if you change something in pytorch array it will not reflect in numpy array
pytorch_array = pytorch_array +1
pytorch_array , nparray_from_pytorch

(tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32))

#Reproducability (trying to take random out of random):

how a neural network learns:
* start with random numbers
* perform tensor operations
* update random numbers to try and make them better representations of the data
* again and again

Any time you create a random tensor , with `torch.rand` , its going to give different numbers every time you run it

To reduce the randomness in neural networks and pytorch , comes the concept of a **random seed**

Setting a random seed in PyTorch is crucial for achieving reproducibility in experiments and debugging. It ensures that operations *relying* on random number generation produce the same results across different runs.

In [ ]:
torch.rand(3,3)

tensor([[0.5314, 0.1197, 0.2840],
        [0.3097, 0.8956, 0.8843],
        [0.3615, 0.6731, 0.3152]])

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
# its highly unlikely that these tensors have some same values
print(random_tensor_A == random_tensor_B)

tensor([[0.1830, 0.2901, 0.4245, 0.3045],
        [0.5474, 0.4404, 0.7304, 0.8722],
        [0.0985, 0.4736, 0.5450, 0.1385]])
tensor([[0.7728, 0.6115, 0.3991, 0.9294],
        [0.9587, 0.9401, 0.4073, 0.4925],
        [0.5309, 0.3167, 0.0560, 0.8165]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


If you share this piece of code with someone else theyre going to get another numbers too and its highly unlikely for them to get same values too

In [ ]:
# This will remain same everytime you run it
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


`torch.manual_seed(random_seed)` generally only works for one block of code below it

* This is a way of flavoring the randomness

In [ ]:
# This will remain same everytime you run it
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

RANDOM_SEED2 = 46
torch.manual_seed(RANDOM_SEED2)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.6611, 0.0600, 0.5174, 0.1596],
        [0.7550, 0.8390, 0.0674, 0.4631],
        [0.1477, 0.3597, 0.9328, 0.0170]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


# Running Tensors and PyTorch objects on the GPUs

GPUs = faster computation on numbers , because of CUDA + NVIDIA hardware + PyTorch working behind to scenes to make everything good.

Using a GPU:

1. Use google colab - easiest method
2. Use your own GPU
3. Use cloud computing - GCP , AWS , Azure
(these services allow you to rent computers on the clous and access them)

2,3 require setting up , use PyTorch's documentation for that

In [ ]:
!nvidia-smi

Fri Jul 18 16:34:56 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

PyTorch requires almost no setup for this

Check for GPU access with pytorch - `torch.cuda.is_available()`

In [ ]:
import torch
torch.cuda.is_available()

True

You might not always have a GPU but if its available you can use it

**Device-agnostic code**: Device-agnostic code in PyTorch refers to writing code that can seamlessly run on different hardware devices, primarily CPUs and GPUs, without requiring significant modifications.

For PyTorch , since its capable of running compute on the GPU or CPU , its best practice to setup device agnostic code

eg: run on GPU if available else default cpu

you can set it using python code too

In [8]:
# set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

If you are running huge models on large datasets , you might want to run one model on certain GPU , another model on another GPU and so on

In [ ]:
# count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is beacuse using a GPU results in faster computations



In [ ]:
# create a tensor (default on cpu)
tensor = torch.tensor([1,2,3] , device = "cpu")
print(tensor , tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to CPU

Another big error in PyTorch is device error , we can not transform a Tensor to NumPy if its on GPU

In [ ]:
# device error:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

To fix the GPU tensor with NumPy issue , we can first set it to the CPU - using `tensor.cpu()` and then convert it to NumPy using `.numpy()`

In [ ]:
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

## PyTorch fundamentals exercises

In [2]:
# 1. Create a random tensor with shape (7, 7).
import torch
random_tensor1 = torch.rand(7,7)
random_tensor1

tensor([[0.6201, 0.6720, 0.8893, 0.7427, 0.9655, 0.3175, 0.5693],
        [0.3430, 0.6589, 0.6834, 0.6554, 0.8966, 0.2952, 0.5029],
        [0.6692, 0.1470, 0.9973, 0.3592, 0.9430, 0.1192, 0.3690],
        [0.6066, 0.8915, 0.3957, 0.0499, 0.1774, 0.1495, 0.3348],
        [0.4232, 0.4864, 0.0960, 0.8527, 0.3632, 0.0926, 0.6067],
        [0.0745, 0.6849, 0.5195, 0.2729, 0.3364, 0.4694, 0.4707],
        [0.5629, 0.6543, 0.1266, 0.1732, 0.0095, 0.7405, 0.4622]])

In [3]:
# 2. Perform a matrix multiplication on the tensor from 2 with another random tensor
#  with shape (1, 7)
random_tensor2 = torch.rand(1,7)
random_tensor2


tensor([[0.1838, 0.8023, 0.5215, 0.8188, 0.6964, 0.6627, 0.0981]])

In [5]:
torch.matmul(random_tensor1 , random_tensor2.T)

tensor([[2.3201],
        [1.5013],
        [2.5941],
        [1.5272],
        [2.5921],
        [1.1787],
        [2.0664]])

In [16]:
# 3. Set the random seed to 0 and do exercises 1 & 2 over again.
RANDOM_SEED3 = 0
torch.manual_seed(RANDOM_SEED3)
random_tensor1_updated = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED3)
random_tensor2_updated = torch.rand(1,7)
print(f" Random tensor 1 with random seed 0 : {random_tensor1_updated}")
print(f" \n Random tensor 2 with random seed 0 : {random_tensor2_updated}")
print(f"\n Matrix multiplication of both tensors : \n {torch.matmul(random_tensor1_updated , random_tensor2_updated.T)}")



 Random tensor 1 with random seed 0 : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
 
 Random tensor 2 with random seed 0 : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

 Matrix multiplication of both tensors : 
 tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


In [20]:
# 4. Speaking of random seeds, we saw how to set it with torch.manual_seed()
#  but is there a GPU equivalent? (hint: you'll need to look into the
# documentation for torch.cuda for this one). If there is,
# set the GPU random seed to 1234.

torch.cuda.manual_seed(1234)

In [10]:
# 5. Create two random tensors of shape (2, 3) and send them both to the
#  GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have
#  to be the GPU random seed).
torch.manual_seed(1234)
A = torch.rand([2,3] , device="cpu")
torch.manual_seed(1234)
B = torch.rand([2,3] , device = "cpu")
A,B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

In [11]:
# remember to run device agnostic code for this one
A.to(device) , B.to(device)

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

In [14]:
# 6. Perform a matrix multiplication on the tensors you created in 5
#  (again, you may have to adjust the shapes of one of the tensors).
mul = A @ B.T
mul

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [17]:
# 7. Find the maximum and minimum values of the output of 6.
torch.max(mul) , torch.min(mul)

(tensor(0.6287), tensor(0.2161))

In [18]:
# 8. Find the maximum and minimum index values of the output of 6.
torch.argmax(mul) , torch.argmin(mul)

(tensor(3), tensor(1))

In [23]:
# 9. Make a random tensor with shape (1, 1, 1, 10) and then create a
# new tensor with all the 1 dimensions removed to be left with a tensor
#  of shape (10). Set the seed to 7 when you create it and print out the
#  first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
x= torch.rand([1,1,1,10])
x

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [24]:
y = torch.squeeze(x)
y

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

In [26]:
print(f"First tensor: {x}")
print(f"\n first tensor's shape : {x.shape}")
print(f"\n Second tensor: {y}")
print(f"\n Second tensor's shape : {y.shape}")

First tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

 first tensor's shape : torch.Size([1, 1, 1, 10])

 Second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

 Second tensor's shape : torch.Size([10])
