In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


**torch.Tensor**:
Tensor is a multi-dimensional matrix containing elements of a single data type.
A scalar is a tensor rank 0, so requires only 1 independent value associated with it

In [ ]:
# intro to tensors

scalar = torch.tensor(6)
print(scalar)
print(scalar.ndim)
print(scalar.shape)

tensor(6)
0
torch.Size([])


In [ ]:
torch.tensor([[1 , 2 , 3] , [ 4, 5 , 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.tensor(np.array([[1 , 2 , 3] , [ 4, 5 , 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().

In [ ]:
torch.zeros([2,4] )


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.zeros([2,4] , dtype = torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
x = torch.tensor([[1,4,6] , [9,5,6]])
print(x[0][2])
x[1][1] = 3

x

tensor(6)


tensor([[1, 4, 6],
        [9, 3, 6]])

In [ ]:
x = torch.tensor([[1]])
print(x)
# get tensor as python int - using item()
x.item()


tensor([[1]])


1

In [ ]:
vector = torch.tensor([1,2,3])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2, 3])
1
torch.Size([3])


In [ ]:
# MATRIX
MATRIX = torch.tensor([[1,2,3] , [4,5,6]])
print(MATRIX)
print(MATRIX[0])
print(MATRIX[1])

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
tensor([4, 5, 6])


In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

**scalar**:
 ndim: no of square brackets -> 0

**vector**:
shape : no of elements
ndim : no of square brackets -> 1

**matrix**:
shape : no of rows , col
ndim : no of square brackets -> 2

**tensor**:
ndim : no of square brackets -> 3 or more

shape : eg : 1 , 3, 3 means 1 3x3 shape tensor ( 1 dimension of 3x3)
very outer bracket matches with 1 , then next one matches with row , last with col

In [ ]:
TENSOR =  torch.tensor([[[1,4,5],
                         [3,4,5],
                         [6,7,4]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 4, 5],
         [3, 4, 5],
         [6, 7, 4]]])
3
torch.Size([1, 3, 3])


In [ ]:
# torch.size([1,3,3])
# indexes : torch.size([0,1,2])
# LOOK AT THE BRACKETS:
TENSOR[0]

tensor([[1, 4, 5],
        [3, 4, 5],
        [6, 7, 4]])

In [ ]:

TENSOR1 =  torch.tensor([[[[1,4,5],
                         [3,4,5],
                         [6,7,4]]]])
TENSOR1.ndim

4

In [ ]:
TENSOR1.shape

torch.Size([1, 1, 3, 3])

In [ ]:
TENSOR2 =  torch.tensor([[[[[1,4,5],
                         [3,4,5],
                         [6,7,4]]]]])
TENSOR2.shape



torch.Size([1, 1, 1, 3, 3])

*A tensor can represent any shape or size, or any combinations of number*





**usually:** a scalar and a vector is written by a lowercase and matrix or tensor is written by uppercase

### random tensors:

In [ ]:
# torch.rand(rows,cols)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6488, 0.9722, 0.6144, 0.6841],
        [0.3304, 0.2033, 0.3597, 0.2098],
        [0.0301, 0.5736, 0.6570, 0.5183]])

In [ ]:
random_tensor.ndim

2

In [ ]:
 random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_TENSOR2 = torch.rand(1,3,4)
random_TENSOR2

tensor([[[0.8180, 0.2025, 0.5471, 0.2795],
         [0.4214, 0.9608, 0.1686, 0.5930],
         [0.6418, 0.9681, 0.9587, 0.6741]]])

In [ ]:
random_TENSOR2.shape

torch.Size([1, 3, 4])

In [ ]:
random_TENSOR2.ndim

3

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3) )
# height , width , color channel = 224 , 224 , 3
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

ALMOST ANY DATA CAN BE REPRESENTED AS TENSORS , ONE OF THE COMMON WAYS OF REPRESENTING IMAGE DATA IS TO COLOR CHANNEL , HEIGHT , WIDTH OR HEIGHT , WIDTH , COLOR CHANNEL


### zeros and ones tensor

In [ ]:
# tensor of all zeroes:
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeroes1 = torch.zeros((3,4))
zeroes1

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_value_tensor = torch.rand(3,4)
random_value_tensor

tensor([[0.9796, 0.5247, 0.0308, 0.6490],
        [0.9727, 0.6428, 0.6725, 0.0653],
        [0.3691, 0.1977, 0.5804, 0.8173]])

In [ ]:
zeroes1*random_value_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# tensor of all ones:
ones = torch.ones((3,4) )
ones , ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# creating a range of tensors and tensors - like

In [ ]:
one_to_ten = torch.arange(1 , 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
step_one_to_twenty = torch.arange(start = 1 , end = 20 , step = 4)
step_one_to_twenty

tensor([ 1,  5,  9, 13, 17])

In [ ]:
#  if we want to create a tensor full of zeros and has the same shape as one_to_ten we can use tensor like or zeros like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor datatypes**

The default dtypes even if we specify as none are int64 for integer and float32 for float

In [ ]:
no_datatype_tensor = torch.tensor([3,6,8] , dtype = None)
no_datatype_tensor.dtype

torch.int64

In [ ]:
no_datatype_tensor = torch.tensor([3.0,6.0,8.0] , dtype = None)
no_datatype_tensor.dtype

torch.float32

In [ ]:
no_datatype_tensor = torch.tensor([3.0,6.0,8.0] , dtype = torch.float16)
no_datatype_tensor.dtype

torch.float16

Some of the important parameters of torch.tensor are dtype , device , requires_grad

you can calculate faster if numbers take less memory
*   single-precision floating-point :float32 (32 bits in computer memory)
*   half-precision floating point :float16

 the **precision** of a numerical quantity is a measure of the detail in which the quantity is expressed

 tensor dtypes is one of the 3 big errors youll run into with pytorch and deep learning:


1.   Tensor not right datatype
2.   Tensor not right shape
3.   Tensor not on right device

**Shape** :same concept as matrix multiplication

**device** : if one tensors on gpu for fast computing and another tensor is on cpu and you want to do some operations on them : then youll run into not right device error.
    device = "cuda"
    or device = "cpu"


**Requires_grad** : if you want pytorch to track gradients when pytorch goes through certain calculations

In [ ]:
float_32_tensor = torch.tensor([3.0 , 5.0 , 7.0] , dtype = torch.float32 ,
                               device = None , requires_grad = False)
float_32_tensor.device

device(type='cpu')

In [ ]:
# we can use either torch.float16 or torch.half
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [ ]:
different_datatype_mul = float_32_tensor*float_16_tensor
different_datatype_mul , different_datatype_mul.dtype

(tensor([ 9., 25., 49.]), torch.float32)

In [ ]:
int_32_tensor = torch.tensor([3,4,5] , dtype = torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 20., 35.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand(4,5)
some_tensor

tensor([[0.3358, 0.9250, 0.8959, 0.8296, 0.2476],
        [0.2331, 0.5850, 0.0561, 0.5420, 0.6586],
        [0.7234, 0.5308, 0.7934, 0.3624, 0.4295],
        [0.3515, 0.2812, 0.7621, 0.2925, 0.3056]])

tensor.shape is an attribute and tensor.size() is a function and both give same values

In [ ]:
print(some_tensor)
print(f"Datatye of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Size of tensor : {some_tensor.size()}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.3358, 0.9250, 0.8959, 0.8296, 0.2476],
        [0.2331, 0.5850, 0.0561, 0.5420, 0.6586],
        [0.7234, 0.5308, 0.7934, 0.3624, 0.4295],
        [0.3515, 0.2812, 0.7621, 0.2925, 0.3056]])
Datatye of tensor : torch.float32
Shape of tensor : torch.Size([4, 5])
Size of tensor : torch.Size([4, 5])
Device tensor is on : cpu


### Manipulating tensors (tensor operations)

Tensor operations include ⁉


1.   Addition
2.   Subtraction
3.   Multiplication(element wise)
4.   Division
5.   Matrix multiplication



In [ ]:
tensor_op_addition = torch.tensor([1,2,3])
tensor_op_addition + 10

tensor([11, 12, 13])

In [ ]:
tensor_op_addition * 10

tensor([10, 20, 30])

In [ ]:
tensor_op_addition - 10

tensor([-9, -8, -7])

In [ ]:
# built in pytorch functions
torch.mul(tensor_op_addition , 20)


tensor([20, 40, 60])